services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails server -b 0.0.0.0"
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: preness_development
      DB_TEST_NAME: preness_test
    env_file:
      - .env
    volumes:
      - .:/app
      - bundle_data:/usr/local/bundle
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: preness_development
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  bundle_data:
  db_data:
